#!/usr/bin/env sh

function getLastGithubTag {
	JSON=$(curl -s https://api.github.com/repos/${1}/${2}/tags | jq '.[0]')

	MEDIAWIKI_TAG_NAME=$(echo ${JSON} | jq '.name' | sed -e 's/"//g')
	MEDIAWIKI_VERSION=$(echo ${MEDIAWIKI_TAG_NAME} | cut -d "." -f 1,2)
	MEDIAWIKI_PATCH=$(echo ${MEDIAWIKI_TAG_NAME} | cut -d "." -f 3)
	MEDIAWIKI_TARBALL=$(echo ${JSON} | jq '.tarball_url' | sed -e 's/"//g')
}

function getLastDockerImage {
	BASE_TAG=$(wget -q https://registry.hub.docker.com/v1/repositories/${1}/tags -O - | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n' | awk -F: '{print $3}' | grep ${2} | sort | tail -n 1)
}

getLastGithubTag wikimedia mediawiki
getLastDockerImage ubuntu bionic-

BASE_VERSION=$(echo ${BASE_TAG} | cut -d "-" -f 2)

MEDIAWIKI_VERSION=1.30
MEDIAWIKI_PATCH=0
DOCKER_TAG=v${MEDIAWIKI_VERSION}.${MEDIAWIKI_PATCH}-${BASE_VERSION}

docker build \
	--tag ${IMAGE_NAME} \
	--build-arg BASE_TAG=${BASE_TAG} \
	--build-arg MEDIAWIKI_VERSION=${MEDIAWIKI_VERSION} \
	--build-arg MEDIAWIKI_PATCH=${MEDIAWIKI_PATCH} \
	.
